#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=10"]
# ///
"""Bake the SEGA fade sprite + per-frame palette table.

The four fade reference PNGs (assets/sega_fade/{1,2,3,4}.png) are the
SAME anti-aliased SEGA wordmark with successively richer palettes —
pale cyan, cyan, mid blue, deep blue. Every pixel position holds a
fixed "depth level" across all four frames; only the colour assigned to
each level changes. Cycling the CI4 palette through those four
assignments at runtime drives the fade-in without re-uploading the
shape.

This script does the offline analysis:

  1. Uses frame 4 (richest distinct-colour count) as the shape source.
  2. Identifies the per-pixel depth level (background + N foreground
     gradient steps).
  3. Writes an indexed PNG with a canonical level→index palette.
     mksprite consumes that PNG with --format CI4 --dither NONE and
     preserves the palette order in the output sprite.
  4. Extracts each frame's colour at each level by sampling one pixel
     per level and emits a C header containing four RGBA16 palettes in
     the same order.

Usage:
  uv run build_fade.py <assets_dir> <out_png> <out_header>
"""

import sys
from PIL import Image
from collections import Counter

if len(sys.argv) != 4:
    sys.exit("usage: build_fade.py <assets_dir> <out_png> <out_header>")

ASSETS_DIR, OUT_PNG, OUT_HEADER = sys.argv[1:4]

# The reference PNGs use two near-white values for bg vs the TM glyph;
# the runtime treats them as one merged "white" level.
BG_RGBS = {(0xFC, 0xFC, 0xFC), (0xFF, 0xFF, 0xFF)}

def load_frame(k: int) -> Image.Image:
    return Image.open(f"{ASSETS_DIR}/{k}.png").convert("RGB")

frames = [load_frame(k) for k in (1, 2, 3, 4)]
W, H = frames[0].size
for fi, fr in enumerate(frames, 1):
    if fr.size != (W, H):
        sys.exit(f"{fi}.png size {fr.size} differs from {1}.png {W,H}")

# Frame 4 (deepest blue) has the most distinct foreground colours,
# one per gradient step, so use it as the shape source.
shape = frames[3]
counts = Counter(shape.getdata())

# Order fg by descending lightness (sum of channels) so level 1 is the
# faintest AA edge and level N-1 is the deepest fully-painted fill.
fg_colours = sorted(
    (c for c in counts if c not in BG_RGBS),
    key=lambda c: -sum(c),
)
levels = [(0xFC, 0xFC, 0xFC)] + fg_colours  # level 0 = bg/TM merged
N = len(levels)
print(f"build_fade: {N} levels (bg + {N-1} fg gradient steps)")

# pixel colour → level index. bg + TM both collapse to level 0.
fg_idx = {c: (i + 1) for i, c in enumerate(fg_colours)}
def to_level(c) -> int:
    return 0 if c in BG_RGBS else fg_idx[c]

# Emit canonical indexed PNG (PNG-8). mksprite preserves the PNG-8
# palette order, so the output sprite's CI4 indices match `levels`.
palette_bytes = []
for c in levels:
    palette_bytes.extend(c)
palette_bytes.extend([0] * (768 - len(palette_bytes)))

out = Image.new("P", (W, H))
out.putpalette(palette_bytes)
shape_pixels = list(shape.getdata())
out.putdata([to_level(c) for c in shape_pixels])
out.save(OUT_PNG)
print(f"build_fade: wrote {OUT_PNG}")

# Sample one pixel position per level (constant across frames).
sample_idx = {}
for i, c in enumerate(shape_pixels):
    lvl = to_level(c)
    if lvl not in sample_idx:
        sample_idx[lvl] = i
    if len(sample_idx) == N:
        break
assert len(sample_idx) == N, "shape source missing one of the detected levels"

def to_rgba16(rgb) -> int:
    r, g, b = rgb
    R = (r >> 3) & 0x1F
    G = (g >> 3) & 0x1F
    B = (b >> 3) & 0x1F
    return (R << 11) | (G << 6) | (B << 1) | 1   # alpha=1 (opaque)

palettes = []
for fi, fr in enumerate(frames):
    fr_pixels = list(fr.getdata())
    entries = [to_rgba16(fr_pixels[sample_idx[lvl]]) for lvl in range(N)]
    # CI4 palettes upload 16 entries; pad the unused slots with 0.
    entries += [0] * (16 - len(entries))
    palettes.append(entries)

# Frame 1 has so few unique colours that several "deep" levels collapse
# onto the same pale-cyan target. That collapse is intentional in the
# source (the deeper detail "develops" frame by frame), so we trust the
# sampled values without complaining.

with open(OUT_HEADER, "w") as f:
    f.write("// AUTO-GENERATED by tools/bake-splash/build_fade.py — do not edit.\n")
    f.write("#pragma once\n\n")
    f.write("#include <cstdint>\n\n")
    f.write(f"constexpr int SPLASH_FADE_FRAMES = {len(palettes)};\n")
    f.write(f"constexpr int SPLASH_FADE_LEVELS = {N};\n\n")
    f.write("// Palette per fade-step (CI4: 16 entries; only the first\n")
    f.write("// SPLASH_FADE_LEVELS slots are meaningful).\n")
    f.write(f"constexpr uint16_t SPLASH_FADE_PALETTES[{len(palettes)}][16] = {{\n")
    for fi, pal in enumerate(palettes):
        f.write(f"    /* frame {fi+1} */ {{")
        f.write(", ".join(f"0x{e:04X}" for e in pal))
        f.write("},\n")
    f.write("};\n")
print(f"build_fade: wrote {OUT_HEADER}")
