/***************************************************************************
    N64 pre-boot SEGA splash — implementation.

    Two-sprite animation:

      Phase 1  Sweep on the CI8 rainbow sprite (sega_sweep.sprite, baked
               from assets/sega_sweep.png). The sprite's pixel data is
               re-indexed at boot so each x-stripe of the wordmark uses
               a unique CI8 slot — a 7-tap white→cyan→white pulse then
               slides through those ~45 slots from left to right at one
               step per frame so only the sweep's cyan ramp ever paints
               over the white background.

      Phase 2  Hand-off to the CI4 fade sprite (sega_fade.sprite, baked
               from assets/sega_fade/4.png with a 7-level palette per
               sega_fade_palettes.h). The runtime cycles through four
               palettes — 4 frames each — to drive the fade-in from
               pale cyan through cyan and mid blue to deep blue.

      Phase 3  Hold for 180 frames on the deepest blue palette (frame 4)
               so the final SEGA blue-on-white silhouette stays on
               screen for three seconds — long enough for the
               accompanying SEGA jingle (sega.wav64, ~2.9 s) to play
               to completion.

      Phase 4  Fade out: two frames each at palettes 2, 1, 0 (mid blue
               → cyan → pale cyan), then two frames on a synthetic
               all-white palette so the wordmark disappears completely
               before the boot menu takes over.

    Holding START at any point during the animation skips the remainder
    of the loop. The current frame still renders and releases its
    framebuffer through rdpq_detach_show; cleanup runs identically to
    the normal exit path. If the user is still holding START when
    boot_menu::run() starts polling, its prompt will detect it and drop
    into the setup UI — same convention boot_menu uses for its own
    held-START prompt window.

    Audio
    -----
    Audio::init() runs *after* the splash in main(), so the splash owns
    its own short-lived audio + mixer bringup: audio_init(22050, 4) and
    mixer_init(2) at run() entry, wav64_play at the fade-phase boundary,
    audio_can_write/mixer_poll inside the per-frame loop to feed the AI
    buffers, and mixer_close / audio_close on the way out so Audio::init
    finds the subsystem in a clean state.

    Cache management
    ----------------
    Both the sprite pixel buffer (sprite_load → asset_load malloc) and
    the per-frame TLUT scratch live in cached CPU memory. We write to
    them through the normal cached pointer and call
    data_cache_hit_writeback on the touched range before the RDP DMA
    reads it (once after the pixel re-index, once per frame for the
    TLUT). Going through UncachedAddr while the cache still holds
    shadow values trips ares' "uncached write to cached line" warning
    and risks any later cached read seeing stale bytes — explicit
    writeback sidesteps both.
***************************************************************************/

#include "splash.hpp"
#include "input.hpp"

// Generated by tools/bake-splash/build_fade.py via cmake/bake-splash.cmake.
// Defines SPLASH_FADE_FRAMES (= 4), SPLASH_FADE_LEVELS (= 7), and
// SPLASH_FADE_PALETTES[4][16] of RGBA16 entries.
#include "sega_fade_palettes.h"

#include <libdragon.h>
#include <cstdint>
#include <cstddef>

namespace
{
    // ---- sweep phase -----------------------------------------------------

    constexpr int  SWEEP_LEN         = 7;
    constexpr int  N_STRIPES_MAX     = 56;
    constexpr int  FRAMES_PER_STEP   = 1;     // 1 frame per sweep step (~1 s)

    constexpr uint32_t SWEEP_SHAPE[SWEEP_LEN] = {
        0xFCFCFC, 0xB4FCFC, 0x48FCFC, 0x00D8FC, 0x48FCFC, 0xB4FCFC, 0xFCFCFC,
    //   white      pale      mid       cyan      mid       pale      white
    //   edge       cyan      cyan      PEAK      cyan      cyan      edge
    };
    constexpr uint32_t WHITE_RGB  = 0xFCFCFC;

    // Sweep-sprite slot layout after re-indexing:
    //   0       = white (bg + TM merged)
    //   1..N    = one slot per x-stripe, left-to-right
    constexpr uint8_t SLOT_WHITE       = 0;
    constexpr uint8_t SLOT_STRIPE_BASE = 1;

    // ---- fade phase ------------------------------------------------------

    constexpr int FRAMES_PER_FADE = 4;        // each fade-in palette held this long
    constexpr int FINAL_HOLD      = 180;      // 3 seconds on the deepest blue

    // Fade-out runs through palettes 2, 1, 0 (FRAMES_PER_FADEOUT each),
    // then holds on a synthetic all-white palette for WHITE_HOLD frames
    // before the boot menu takes over.
    constexpr int FADEOUT_STEPS      = SPLASH_FADE_FRAMES - 1;  // 3 palette steps
    constexpr int FRAMES_PER_FADEOUT = 2;                       // each step held this long
    constexpr int WHITE_HOLD         = 2;                       // frames at all-white
    constexpr int FADEOUT_FRAMES =
        FADEOUT_STEPS * FRAMES_PER_FADEOUT + WHITE_HOLD;

    // ---- audio -----------------------------------------------------------

    constexpr int AUDIO_RATE     = 22050;     // wav64 was resampled to this
    constexpr int AUDIO_BUFFERS  = 4;         // ~160 ms slack at 22050 Hz
    constexpr int AUDIO_MIXER_CH = 2;         // stereo wav64 uses ch 0 + 1

    // Largest TLUT we ever upload — the sweep phase uses
    // SLOT_STRIPE_BASE + n_stripes entries, capped by N_STRIPES_MAX; the
    // fade phase only uses the first 16. Keeps the per-frame scratch on
    // run()'s stack so the splash leaves zero BSS footprint behind.
    constexpr int SCRATCH_TLUT_ENTRIES = SLOT_STRIPE_BASE + N_STRIPES_MAX;

    inline uint16_t rgb_to_rgba16(uint32_t rgb)
    {
        const uint8_t r = (uint8_t)((rgb >> 16) & 0xFF);
        const uint8_t g = (uint8_t)((rgb >>  8) & 0xFF);
        const uint8_t b = (uint8_t)( rgb        & 0xFF);
        return color_to_packed16(RGBA32(r, g, b, 0xFF));
    }

    inline uint16_t rgb_to_15bit_key(uint32_t rgb)
    {
        return (uint16_t)(((rgb >> 19) & 0x1F) << 10 |
                          ((rgb >> 11) & 0x1F) <<  5 |
                          ((rgb >>  3) & 0x1F));
    }

    int find_white_slot(const uint16_t* tlut, int n)
    {
        const uint16_t key = rgb_to_15bit_key(WHITE_RGB);
        for (int i = 0; i < n; ++i)
            if ((tlut[i] >> 1) == key) return i;
        return -1;
    }

    // Walk the sweep sprite's CI8 pixel buffer once, mapping every hue
    // pixel (anything not the original white slot) to a unique stripe
    // slot keyed by x. Returns the number of stripes detected. The
    // caller is responsible for the writeback that publishes the new
    // indices to RDRAM before the first blit.
    int reindex_pixels(uint8_t* data, int W, int H, int stride,
                       uint8_t orig_white_slot)
    {
        int n_stripes     = 0;
        int last_hue_slot = -1;
        for (int x = 0; x < W; ++x)
        {
            int hue_at_x = -1;
            for (int y = 0; y < H; ++y)
            {
                const int idx = data[y * stride + x];
                if (idx != orig_white_slot) { hue_at_x = idx; break; }
            }
            if (hue_at_x < 0)
            {
                // Pure background column.
                for (int y = 0; y < H; ++y)
                    if (data[y * stride + x] == orig_white_slot)
                        data[y * stride + x] = SLOT_WHITE;
                continue;
            }
            if (hue_at_x != last_hue_slot)
            {
                ++n_stripes;
                last_hue_slot = hue_at_x;
            }
            assertf(n_stripes <= N_STRIPES_MAX,
                "splash: sega_sweep.sprite has more than %d stripes (raise N_STRIPES_MAX)",
                N_STRIPES_MAX);
            const uint8_t new_slot = (uint8_t)(SLOT_STRIPE_BASE + (n_stripes - 1));
            for (int y = 0; y < H; ++y)
            {
                const int idx = data[y * stride + x];
                data[y * stride + x] =
                    (idx == orig_white_slot) ? SLOT_WHITE : new_slot;
            }
        }
        return n_stripes;
    }

    // Phase 1 — write the sweep TLUT into the scratch.
    void compute_sweep_palette(int f, int n_stripes, uint16_t* tlut)
    {
        const int step       = f / FRAMES_PER_STEP;
        const int sweep_left = step - (SWEEP_LEN - 1);
        for (int i = 0; i < n_stripes; ++i)
        {
            const uint32_t rgb =
                (i >= sweep_left && i < sweep_left + SWEEP_LEN)
                    ? SWEEP_SHAPE[i - sweep_left]
                    : WHITE_RGB;
            tlut[SLOT_STRIPE_BASE + i] = rgb_to_rgba16(rgb);
        }
        tlut[SLOT_WHITE] = rgb_to_rgba16(WHITE_RGB);
    }

    // Phases 2/3 — copy the active fade palette into the scratch.
    void copy_fade_palette(int frame_idx, uint16_t* tlut)
    {
        const uint16_t* src = SPLASH_FADE_PALETTES[frame_idx];
        for (int i = 0; i < 16; ++i) tlut[i] = src[i];
    }

    // Final fade-out frame — every entry is white so the wordmark
    // disappears completely against the white background.
    void fill_white_palette(uint16_t* tlut)
    {
        const uint16_t w = rgb_to_rgba16(WHITE_RGB);
        for (int i = 0; i < 16; ++i) tlut[i] = w;
    }

    // Round a byte count up to a full 16-byte cache line so
    // data_cache_hit_writeback covers every line the touched range
    // straddles.
    inline size_t cacheline_round_up(size_t n)
    {
        return (n + 15u) & ~size_t{15};
    }
}

namespace n64 { namespace splash
{

void run()
{
    // ---- audio bringup ---------------------------------------------------
    // Audio::init() hasn't run yet — own the audio + mixer here and tear
    // them back down before returning so Audio::init() can claim them
    // fresh.

    audio_init(AUDIO_RATE, AUDIO_BUFFERS);
    mixer_init(AUDIO_MIXER_CH);

    wav64_t splash_wav;
    wav64_open(&splash_wav, "rom:/splash/sega.wav64");

    // ---- sweep sprite: load + re-index -----------------------------------

    sprite_t* sweep_sprite = sprite_load("rom:/splash/sega_sweep.sprite");
    assertf(sweep_sprite, "splash: sprite_load(rom:/splash/sega_sweep.sprite) failed");

    uint16_t* sweep_pal     = sprite_get_palette(sweep_sprite);
    const int sweep_pal_n   = sprite_get_palette_used_colors(sweep_sprite);
    const int orig_white    = find_white_slot(sweep_pal, sweep_pal_n);
    assertf(orig_white >= 0,
        "splash: white (#FCFCFC) missing from sega_sweep.sprite TLUT");

    surface_t sweep_pix     = sprite_get_pixels(sweep_sprite);
    uint8_t*  sweep_buf     = (uint8_t*)sweep_pix.buffer;
    const int n_stripes     = reindex_pixels(
        sweep_buf, sweep_pix.width, sweep_pix.height, sweep_pix.stride,
        (uint8_t)orig_white);
    // Publish the re-indexed pixels to RDRAM so rdpq_tex_blit's DMA reads
    // the new indices. CI8 stride matches width (320), and surface_make
    // returns 16-byte-aligned buffers, so the whole range is cache-line
    // aligned.
    data_cache_hit_writeback(sweep_buf,
                             (size_t)sweep_pix.height * sweep_pix.stride);

    // ---- fade sprite: load only (palette comes from the generated header)

    sprite_t* fade_sprite  = sprite_load("rom:/splash/sega_fade.sprite");
    assertf(fade_sprite, "splash: sprite_load(rom:/splash/sega_fade.sprite) failed");
    surface_t fade_pix     = sprite_get_pixels(fade_sprite);

    // ---- phase boundaries ------------------------------------------------

    const int sweep_steps       = n_stripes + SWEEP_LEN - 1;
    const int phase_sweep_end   = sweep_steps * FRAMES_PER_STEP;
    const int phase_fadein_end  = phase_sweep_end + SPLASH_FADE_FRAMES * FRAMES_PER_FADE;
    const int phase_hold_end    = phase_fadein_end + FINAL_HOLD;
    const int total_frames      = phase_hold_end + FADEOUT_FRAMES;

    const int sweep_tlut_count = SLOT_STRIPE_BASE + n_stripes;

    alignas(16) uint16_t scratch_tlut[SCRATCH_TLUT_ENTRIES];

    // Per-frame writeback covers the largest TLUT we ever touch (sweep
    // phase: SLOT_WHITE + sweep_tlut_count entries); round up to a full
    // 16-byte cache line so the writeback covers every dirty line.
    const size_t sweep_wb_bytes =
        cacheline_round_up((size_t)sweep_tlut_count * sizeof(uint16_t));
    const size_t fade_wb_bytes = 16 * sizeof(uint16_t);  // 32, already aligned

    for (int f = 0; f < total_frames; ++f)
    {
        surface_t* fb = display_get();

        // Held START skips the rest of the intro. We still render this
        // frame and release the framebuffer through rdpq_detach_show
        // before breaking — otherwise display_get's bookkeeping leaves
        // the buffer claimed and the boot menu's next display_get blocks.
        // Same convention boot_menu's prompt_for_setup uses.
        input.poll();
        const bool skip = input.is_pressed(Input::START);

        // Start the jingle exactly when the fade phase begins.
        if (f == phase_sweep_end)
            wav64_play(&splash_wav, 0);

        // Drain any empty AI buffers so the mixer keeps the stream flowing.
        // Once wav64_play has run, mixer_poll emits the jingle's samples;
        // before that it fills the buffers with silence.
        while (audio_can_write())
        {
            short* buf = audio_write_begin();
            mixer_poll(buf, audio_get_buffer_length());
            audio_write_end();
        }

        rdpq_attach(fb, NULL);
        rdpq_set_mode_standard();
        rdpq_mode_tlut(TLUT_RGBA16);

        if (f < phase_sweep_end)
        {
            compute_sweep_palette(f, n_stripes, scratch_tlut);
            data_cache_hit_writeback(scratch_tlut, sweep_wb_bytes);
            rdpq_tex_upload_tlut(scratch_tlut, 0, sweep_tlut_count);
            rdpq_tex_blit(&sweep_pix, 0, 0, NULL);
        }
        else
        {
            // Fade-in: cycle through SPLASH_FADE_FRAMES palettes
            // (FRAMES_PER_FADE each).
            // Hold:    deepest palette for FINAL_HOLD frames.
            // Fade-out: drop one palette per frame from palette 2 down to
            //           palette 0, then a synthetic all-white frame so
            //           the wordmark disappears into the background.
            if (f < phase_fadein_end)
            {
                copy_fade_palette((f - phase_sweep_end) / FRAMES_PER_FADE,
                                  scratch_tlut);
            }
            else if (f < phase_hold_end)
            {
                copy_fade_palette(SPLASH_FADE_FRAMES - 1, scratch_tlut);
            }
            else
            {
                const int out_rel = f - phase_hold_end;  // 0..FADEOUT_FRAMES-1
                if (out_rel < FADEOUT_STEPS * FRAMES_PER_FADEOUT)
                    copy_fade_palette(
                        FADEOUT_STEPS - 1 - (out_rel / FRAMES_PER_FADEOUT),
                        scratch_tlut);                   // palettes 2,1,0
                else
                    fill_white_palette(scratch_tlut);    // WHITE_HOLD frames
            }
            data_cache_hit_writeback(scratch_tlut, fade_wb_bytes);
            rdpq_tex_upload_tlut(scratch_tlut, 0, 16);
            rdpq_tex_blit(&fade_pix, 0, 0, NULL);
        }

        rdpq_detach_show();

        input.frame_done();
        if (skip) break;
    }

    // rdpq_detach_show is async (see feedback_rdpq_free_needs_drain memory):
    // sprite_free before the last frame's RDP work completes would hand the
    // palette pages back to the heap while the RDP is still DMA-ing them.
    rspq_wait();
    sprite_free(fade_sprite);
    sprite_free(sweep_sprite);

    // Hand the audio + mixer back to the system clean so Audio::init() can
    // claim them.
    wav64_close(&splash_wav);
    mixer_close();
    audio_close();
}

}}
